from __future__ import annotations

from dataclasses import dataclass
from typing import Callable

import numpy as np

from cv_course.algorithms.image_handlers import IMAGE_HANDLERS
from cv_course.algorithms.video_handlers import VIDEO_HANDLERS
from cv_course.state import ImageSettings, VideoSettings


@dataclass(frozen=True)
class AlgorithmSpec:
    id: str
    title: str
    category: str  # "image" | "video"
    principle: str
    function_desc: str
    example: str
    usage_py: str


def _specs() -> list[AlgorithmSpec]:
    return [
        AlgorithmSpec(
            "img_original",
            "原图",
            "image",
            "未处理的 BGR 图像，作为后续算子的输入。",
            "作为对照，观察各算法相对原图的变化。",
            "输入照片，输出仍为像素矩阵。",
            "import cv2\nimg = cv2.imread('a.jpg')\ncv2.imshow('src', img)\ncv2.waitKey(0)",
        ),
        AlgorithmSpec(
            "img_rotate",
            "旋转",
            "image",
            "仿射变换：绕图像中心旋转 θ 角，可用 2×3 矩阵 M 与 warpAffine 实现。",
            "修正方向或生成数据增强样本。",
            "将风景照旋转 15° 观察裁切与插值。",
            "import cv2\n(h,w)=img.shape[:2]\nM=cv2.getRotationMatrix2D((w/2,h/2),15,1)\nout=cv2.warpAffine(img,M,(w,h))",
        ),
        AlgorithmSpec(
            "img_scale",
            "缩放",
            "image",
            "重采样改变分辨率：最近邻、双线性、双三次等。",
            "统一尺寸、金字塔多尺度分析。",
            "将图缩小到一半再放大，观察细节损失。",
            "import cv2\nout=cv2.resize(img,None,fx=0.5,fy=0.5,interpolation=cv2.INTER_LINEAR)",
        ),
        AlgorithmSpec(
            "img_flip_h",
            "水平反转",
            "image",
            "沿竖直中轴镜像，索引映射 i' = W-1-i。",
            "镜像数据、对称物体。",
            "人脸左右翻转。",
            "import cv2\nout=cv2.flip(img,1)",
        ),
        AlgorithmSpec(
            "img_flip_v",
            "垂直反转",
            "image",
            "沿水平中轴镜像。",
            "修正倒置图像。",
            "将图像上下颠倒。",
            "import cv2\nout=cv2.flip(img,0)",
        ),
        AlgorithmSpec(
            "img_add",
            "加法",
            "image",
            "逐像素饱和加法 cv2.add，避免 uint8 环绕。",
            "提亮、与常数或第二幅图融合。",
            "为暗图加上常数偏置。",
            "import cv2\nout=cv2.add(img,50)",
        ),
        AlgorithmSpec(
            "img_sub",
            "减法",
            "image",
            "cv2.subtract 饱和减法。",
            "背景差分、对比变化。",
            "从图像减去常数变暗。",
            "import cv2\nout=cv2.subtract(img,40)",
        ),
        AlgorithmSpec(
            "img_mul",
            "乘法",
            "image",
            "缩放像素强度，注意裁剪到 [0,255]。",
            "对比度拉伸、增益。",
            "将浮点系数 1.2 乘到像素上再 clip。",
            "import cv2, numpy as np\nout=np.clip(img.astype(np.float32)*1.2,0,255).astype(np.uint8)",
        ),
        AlgorithmSpec(
            "img_threshold",
            "二值化",
            "image",
            "固定阈值 T：大于 T 为前景，否则为背景。",
            "分割文字、简单物体。",
            "扫描文档二值化。",
            "import cv2\ngray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)\n_,th=cv2.threshold(gray,127,255,cv2.THRESH_BINARY)",
        ),
        AlgorithmSpec(
            "img_mask",
            "掩码",
            "image",
            "用单通道 mask 与按位与保留感兴趣区域。",
            "抠图、区域统计。",
            "用阈值生成 mask 后只保留物体。",
            "import cv2\nmask=cv2.inRange(hsv,low,high)\nout=cv2.bitwise_and(img,img,mask=mask)",
        ),
        AlgorithmSpec(
            "img_ch_b",
            "通道拆解(B)",
            "image",
            "多通道矩阵按通道分离，可单独可视化 B。",
            "分析颜色分量、去雾预处理。",
            "只显示蓝色分量。",
            "import cv2\nb,g,r=cv2.split(img)\nzeros=np.zeros_like(b)\nvis=cv2.merge([b,zeros,zeros])",
        ),
        AlgorithmSpec(
            "img_ch_g",
            "通道拆解(G)",
            "image",
            "分离绿色通道。",
            "植被指数、亮度近似。",
            "只显示绿色分量。",
            "import cv2\nb,g,r=cv2.split(img)",
        ),
        AlgorithmSpec(
            "img_ch_merge",
            "通道合并",
            "image",
            "cv2.merge 将单通道合成多通道。",
            "重组处理后的分量。",
            "合并 BGR 三幅灰度图。",
            "import cv2\nout=cv2.merge([b,g,r])",
        ),
        AlgorithmSpec(
            "img_hsv",
            "HSV 物体提取",
            "image",
            "HSV 色域对光照更稳定，inRange 得二值掩码。",
            "彩色目标分割。",
            "提取红色瓶盖区域。",
            "import cv2\nhsv=cv2.cvtColor(img,cv2.COLOR_BGR2HSV)\nmask=cv2.inRange(hsv,low,high)",
        ),
        AlgorithmSpec(
            "img_affine",
            "仿射变换",
            "image",
            "仿射保持平行线：6 自由度，由三对点求 M。",
            "校正透视近似、对齐。",
            "倾斜文本校正。",
            "import cv2\nM=cv2.getAffineTransform(pts1,pts2)\nout=cv2.warpAffine(img,M,(w,h))",
        ),
        AlgorithmSpec(
            "img_hist_gray",
            "灰度直方图",
            "image",
            "统计灰度级频数 h(k)，归一化即概率。",
            "分析曝光、双峰分割。",
            "欠曝图像直方图集中在暗端。",
            "import cv2\nhist=cv2.calcHist([gray],[0],None,[256],[0,256])",
        ),
        AlgorithmSpec(
            "img_hist_color",
            "彩色直方图",
            "image",
            "分通道统计 B/G/R 直方图。",
            "色彩平衡分析。",
            "对比原图与偏色图的三通道直方图。",
            "import cv2\nh=cv2.calcHist([img],[0],None,[256],[0,256])",
        ),
        AlgorithmSpec(
            "img_hist_eq",
            "直方图均衡",
            "image",
            "灰度均衡使灰度分布更均匀；彩色常在 Y 通道做均衡。",
            "增强整体对比度。",
            "逆光人脸提亮。",
            "import cv2\neq=cv2.equalizeHist(gray)",
        ),
        AlgorithmSpec(
            "img_hist_cmp",
            "直方图比较",
            "image",
            "cv2.compareHist 支持相关、卡方、巴氏距离等。",
            "图像检索、变化检测。",
            "比较原图与均衡后直方图的相关性。",
            "import cv2\nd=cv2.compareHist(h1,h2,cv2.HISTCMP_CORREL)",
        ),
        AlgorithmSpec(
            "img_q_single",
            "单阈值量化",
            "image",
            "单阈值将连续灰度映射到两档。",
            "二值分割。",
            "Otsu 可自动选阈值。",
            "import cv2\n_,th=cv2.threshold(gray,0,255,cv2.THRESH_BINARY+cv2.THRESH_OTSU)",
        ),
        AlgorithmSpec(
            "img_q_double",
            "双阈值量化",
            "image",
            "两阈值形成三段或用于 Canny 滞后阈值思想。",
            "边缘连接、区域分层。",
            "高阈值保留强边缘，低阈值连接弱边缘。",
            "import cv2\nedges=cv2.Canny(gray,t1,t2)",
        ),
        AlgorithmSpec(
            "img_thresh_zero",
            "置零阈值",
            "image",
            "THRESH_TOZERO：低于阈值置 0，高于保留。",
            "抑制弱响应。",
            "弱化阴影细节。",
            "import cv2\n_,th=cv2.threshold(gray,127,255,cv2.THRESH_TOZERO)",
        ),
        AlgorithmSpec(
            "img_adaptive",
            "自适应阈值",
            "image",
            "局部邻域统计阈值，适应光照不均。",
            "文档扫描、不均匀照明。",
            "光照不匀的纸张二值化。",
            "import cv2\nth=cv2.adaptiveThreshold(gray,255,cv2.ADAPTIVE_THRESH_GAUSSIAN_C,cv2.THRESH_BINARY,11,2)",
        ),
        AlgorithmSpec(
            "img_conv2d",
            "二维卷积",
            "image",
            "可分离卷积核加速；filter2D 实现线性滤波。",
            "平滑、锐化、边缘响应。",
            "拉普拉斯核增强边缘。",
            "import cv2\nk=np.array([[-1,-1,-1],[-1,8,-1],[-1,-1,-1]])\nout=cv2.filter2D(gray,-1,k)",
        ),
        AlgorithmSpec(
            "morph_erode",
            "腐蚀",
            "image",
            "结构元素范围内取最小值，缩小亮区域。",
            "去噪点、分离物体。",
            "去除二值图像小白点噪声。",
            "import cv2\ner=cv2.erode(bin,kernel)",
        ),
        AlgorithmSpec(
            "morph_dilate",
            "膨胀",
            "image",
            "结构元素范围内取最大值，扩大亮区域。",
            "填充孔洞、连接区域。",
            "加粗笔画。",
            "import cv2\nd=cv2.dilate(bin,kernel)",
        ),
        AlgorithmSpec(
            "morph_close",
            "闭运算",
            "image",
            "先膨胀后腐蚀：闭合小孔、连接邻近物体。",
            "填充轮廓内缝隙。",
            "连接断裂的条形码竖线。",
            "import cv2\nout=cv2.morphologyEx(bin,cv2.MORPH_CLOSE,kernel)",
        ),
        AlgorithmSpec(
            "morph_open",
            "开运算",
            "image",
            "先腐蚀后膨胀：去小突起。",
            "平滑轮廓、去毛刺。",
            "去除椒盐亮噪点。",
            "import cv2\nout=cv2.morphologyEx(bin,cv2.MORPH_OPEN,kernel)",
        ),
        AlgorithmSpec(
            "morph_grad",
            "形态学梯度",
            "image",
            "膨胀图与腐蚀图之差，突出边界。",
            "物体轮廓增强。",
            "二值细胞边缘。",
            "import cv2\nout=cv2.morphologyEx(bin,cv2.MORPH_GRADIENT,kernel)",
        ),
        AlgorithmSpec(
            "morph_tophat",
            "顶帽",
            "image",
            "原图减开运算，突出比邻域亮的小细节。",
            "不均匀背景上的暗小目标检测。",
            "芯片表面微小亮点。",
            "import cv2\nout=cv2.morphologyEx(gray,cv2.MORPH_TOPHAT,kernel)",
        ),
        AlgorithmSpec(
            "morph_blackhat",
            "黑帽",
            "image",
            "闭运算减原图，突出比邻域暗的结构。",
            "暗细节、裂缝。",
            "道路裂缝增强。",
            "import cv2\nout=cv2.morphologyEx(gray,cv2.MORPH_BLACKHAT,kernel)",
        ),
        AlgorithmSpec(
            "edge_laplace",
            "拉普拉斯边缘",
            "image",
            "二阶导数零交叉检测边缘，对噪声敏感。",
            "锐化、边缘位置。",
            "简单几何形状轮廓。",
            "import cv2\nlap=cv2.Laplacian(gray,cv2.CV_16S,ksize=3)",
        ),
        AlgorithmSpec(
            "edge_canny",
            "Canny 边缘",
            "image",
            "高斯平滑、梯度幅角、双阈值滞后、非极大抑制。",
            "高质量单像素宽边缘。",
            "工业零件轮廓提取。",
            "import cv2\ne=cv2.Canny(gray,50,150)",
        ),
        AlgorithmSpec(
            "edge_sobel",
            "Sobel 边缘",
            "image",
            "一阶差分近似偏导，Gx、Gy 合成幅值。",
            "快速梯度、方向性边缘。",
            "水平/垂直边缘分量可视化。",
            "import cv2\ngx=cv2.Sobel(gray,cv2.CV_16S,1,0,ksize=3)",
        ),
        AlgorithmSpec(
            "edge_scharr",
            "Scharr 边缘",
            "image",
            "Sobel 的 3×3 更精确变体，核固定。",
            "比 Sobel(3) 更精确的梯度。",
            "小结构边缘。",
            "import cv2\ngx=cv2.Scharr(gray,cv2.CV_16S,1,0)",
        ),
        AlgorithmSpec(
            "img_contours",
            "轮廓检测",
            "image",
            "findContours 从二值图提取边界链；可计算面积周长。",
            "形状分析、物体计数。",
            "统计硬币个数。",
            "import cv2\ncnts,_=cv2.findContours(th,cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE)",
        ),
        AlgorithmSpec(
            "img_stitch",
            "图像拼接",
            "image",
            "特征匹配估计单应性，投影融合；Stitcher 高级 API。",
            "全景图、宽视野。",
            "两张相邻街景拼接。",
            "import cv2\nst=cv2.Stitcher_create()\nstatus,pano=st.stitch([a,b])",
        ),
        AlgorithmSpec(
            "filt_gray",
            "灰度滤镜",
            "image",
            "Y = 0.299R+0.587G+0.114B 或 BT.601。",
            "去色、为下游算法准备单通道。",
            "人像黑白风格。",
            "import cv2\ng=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)",
        ),
        AlgorithmSpec(
            "filt_vintage",
            "怀旧滤镜",
            "image",
            "色温矩阵或查表，使高光偏黄、暗部偏青。",
            "复古色调。",
            "老照片风格。",
            "import cv2\n# 常用 3x3 颜色矩阵乘每像素向量",
        ),
        AlgorithmSpec(
            "filt_emboss",
            "浮雕滤镜",
            "image",
            "方向性高通卷积 + 偏置产生阴影立体感。",
            "艺术效果。",
            "金属浮雕商标。",
            "import cv2\nkernel=[[-2,-1,0],[-1,1,1],[0,1,2]]\nout=cv2.filter2D(gray,-1,kernel)+128",
        ),
        AlgorithmSpec(
            "filt_blur",
            "模糊滤镜",
            "image",
            "高斯低通平滑，σ 控制频带。",
            "降噪、景深模拟。",
            "人像皮肤柔化。",
            "import cv2\nout=cv2.GaussianBlur(img,(5,5),0)",
        ),
        AlgorithmSpec(
            "filt_sharpen",
            "锐化滤镜",
            "image",
            "原图 + k*(原图-模糊) 或拉普拉斯锐化核。",
            "增强边缘与纹理。",
            "模糊后补偿。",
            "import cv2\nk=np.array([[0,-1,0],[-1,5,-1],[0,-1,0]])\nout=cv2.filter2D(img,-1,k)",
        ),
        AlgorithmSpec(
            "vid_original",
            "原始画面",
            "video",
            "不做处理，直接显示采集到的 BGR 帧。",
            "与其它算法子窗口对照，观察各算子相对原画面的变化。",
            "摄像头预览、确认曝光与白平衡。",
            "import cv2\n# 原帧即 cap.read() 返回的 frame\nout = frame.copy()",
        ),
        AlgorithmSpec(
            "vid_gray",
            "视频转灰度",
            "video",
            "每帧 cvtColor BGR→GRAY。",
            "降低算力、某些检测只需亮度。",
            "监控画面灰度显示。",
            "import cv2\ng=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)",
        ),
        AlgorithmSpec(
            "vid_haar",
            "Haar 分类器",
            "video",
            "Viola-Jones：积分图加速 Haar 特征 + AdaBoost 级联。",
            "实时人脸/眼检测。",
            "摄像头人脸框。",
            "import cv2\ncascade=cv2.CascadeClassifier(xml)\nfaces=cascade.detectMultiScale(gray,1.1,5)",
        ),
        AlgorithmSpec(
            "vid_hog",
            "HOG+SVM",
            "video",
            "梯度方向直方图描述子 + 线性 SVM。",
            "行人检测经典管线。",
            "街景行人框。",
            "import cv2\nhog=cv2.HOGDescriptor()\nhog.setSVMDetector(cv2.HOGDescriptor_getDefaultPeopleDetector())",
        ),
        AlgorithmSpec(
            "vid_match_sqdiff",
            "平方差匹配",
            "video",
            "TM_SQDIFF：模板与窗口差方和，越小越相似。",
            "模板定位。",
            "在画面中找小图标位置。",
            "import cv2\nres=cv2.matchTemplate(img,tpl,cv2.TM_SQDIFF)",
        ),
        AlgorithmSpec(
            "vid_match_sqdiff_n",
            "归一化平方差",
            "video",
            "TM_SQDIFF_NORMED，光照变化更稳。",
            "相似度归一化比较。",
            "不同亮度下的模板匹配。",
            "import cv2\nres=cv2.matchTemplate(img,tpl,cv2.TM_SQDIFF_NORMED)",
        ),
        AlgorithmSpec(
            "vid_match_ccorr",
            "相关匹配",
            "video",
            "TM_CCORR：互相关，越大越相似（受亮度影响）。",
            "简单纹理对齐。",
            "子图在大图中滑动搜索。",
            "import cv2\nres=cv2.matchTemplate(img,tpl,cv2.TM_CCORR)",
        ),
        AlgorithmSpec(
            "vid_match_ccorr_n",
            "归一化相关",
            "video",
            "TM_CCORR_NORMED。",
            "减轻亮度影响的相关匹配。",
            "商标检测。",
            "import cv2\nres=cv2.matchTemplate(img,tpl,cv2.TM_CCORR_NORMED)",
        ),
        AlgorithmSpec(
            "vid_match_coeff",
            "相关系数",
            "video",
            "TM_CCOEFF：去均值相关。",
            "对线性光照变化更鲁棒。",
            "工业定位。",
            "import cv2\nres=cv2.matchTemplate(img,tpl,cv2.TM_CCOEFF)",
        ),
        AlgorithmSpec(
            "vid_match_coeff_n",
            "归一化相关系数",
            "video",
            "TM_CCOEFF_NORMED，最常用之一。",
            "模板匹配首选之一。",
            "UI 自动化找按钮。",
            "import cv2\nres=cv2.matchTemplate(img,tpl,cv2.TM_CCOEFF_NORMED)",
        ),
        AlgorithmSpec(
            "vid_motion",
            "运动检测",
            "video",
            "帧间差分或背景减除，阈值化得运动掩码。",
            "入侵检测、录像触发。",
            "摄像头前挥手触发区域变化。",
            "import cv2\ndiff=cv2.absdiff(prev,gray)\n_,m=cv2.threshold(diff,25,255,cv2.THRESH_BINARY)",
        ),
        AlgorithmSpec(
            "vid_meanshift",
            "MeanShift 跟踪",
            "video",
            "在特征空间沿密度梯度上升迭代，收敛到模式。",
            "彩色直方图目标跟踪。",
            "跟踪彩色球。",
            "import cv2\n_,win=cv2.meanShift(bp,win,term)",
        ),
        AlgorithmSpec(
            "vid_camshift",
            "CamShift 跟踪",
            "video",
            "MeanShift + 对跟踪窗自适应调整尺度/朝向。",
            "尺度变化目标。",
            "走近摄像头的人脸椭圆窗。",
            "import cv2\nret,win=cv2.CamShift(bp,win,term)",
        ),
        AlgorithmSpec(
            "vid_mog",
            "MOG 背景建模",
            "video",
            "混合高斯每个像素多模态，适应缓慢变化背景。",
            "室外监控前景提取。",
            "树叶摇动下的行人。",
            "import cv2\nmog=cv2.bgsegm.createBackgroundSubtractorMOG()\nfg=mog.apply(frame)",
        ),
        AlgorithmSpec(
            "vid_mog2",
            "MOG2 背景建模",
            "video",
            "改进的 GMM，支持阴影检测等。",
            "更稳定的前景分割。",
            "室内灯光渐变。",
            "import cv2\nm=cv2.createBackgroundSubtractorMOG2(500,16,True)\nfg=m.apply(frame)",
        ),
        AlgorithmSpec(
            "vid_yolo_det",
            "YOLO 目标检测",
            "video",
            "Ultralytics YOLO：单阶段检测，支持官方 .pt 或 `yolo export` 得到的 ONNX/engine 等。",
            "多类别框检测与可视化。",
            "街景中同时检出车辆与行人。",
            "from ultralytics import YOLO\nmodel = YOLO('yolo11n.pt')\nresults = model.predict(frame)\nout = results[0].plot()",
        ),
        AlgorithmSpec(
            "vid_yolo_rec",
            "YOLO 目标识别",
            "video",
            "与检测同一 Ultralytics 模型；本软件在识别视图中突出显示当前帧类别名称汇总。",
            "从检测结果归纳类别标签，便于理解「识别」语义。",
            "与检测相同模型路径，界面叠加「识别: 类别A、类别B」文案。",
            "from ultralytics import YOLO\nmodel = YOLO('yolo11n.pt')\nresults = model.predict(frame)\n# 从 results[0].boxes 读取 cls 与 names",
        ),
    ]


SPECS: list[AlgorithmSpec] = _specs()
_BY_ID: dict[str, AlgorithmSpec] = {s.id: s for s in SPECS}


def get_algorithm(aid: str) -> AlgorithmSpec | None:
    return _BY_ID.get(aid)


def iter_algorithms(category: str | None = None) -> list[AlgorithmSpec]:
    if category is None:
        return list(SPECS)
    return [s for s in SPECS if s.category == category]


def apply_image_algorithm(aid: str, img: np.ndarray, params: ImageSettings) -> np.ndarray:
    fn: Callable[..., np.ndarray] | None = IMAGE_HANDLERS.get(aid)
    if fn is None:
        return img
    return fn(img, params)


def apply_video_algorithm(
    aid: str, frame: np.ndarray, params: VideoSettings, engine: object | None
) -> np.ndarray:
    fn = VIDEO_HANDLERS.get(aid)
    if fn is None:
        return frame
    return fn(frame, params, engine)
